### ISSUE TITLE
recognize task build failed 

### ISSUE THREAD

**Issue by xiaoxielnino** [ispras/atr4s#5]
hello, after executed the below command:
'./gradlew recognize -Pdataset=acl2 -PtopCount=10 -Pconfig=CValue.conf -Poutput=cvalueterms.txt' 
I've got the below failed eror, still not known which part went wrong:

Starting a Gradle Daemon (subsequent builds will be faster)
:compileJava NO-SOURCE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:recognize
INFO  AutomaticTermsRecognizer$ - Using chosen topCount: 10
INFO  AutomaticTermsRecognizer$ - Using serialized ATR config: CValue.conf
Exception in thread "main" java.io.FileNotFoundException: CValue.conf (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at ru.ispras.atr.utils.JsonSer$.readFile(JsonSer.scala:26)
        at ru.ispras.atr.AutomaticTermsRecognizer$.delayedEndpoint$ru$ispras$atr$AutomaticTermsRecognizer$1(AutomaticTermsRecognizer.scala:118)
        at ru.ispras.atr.AutomaticTermsRecognizer$delayedInit$body.apply(AutomaticTermsRecognizer.scala:101)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at ru.ispras.atr.AutomaticTermsRecognizer$.main(AutomaticTermsRecognizer.scala:101)
        at ru.ispras.atr.AutomaticTermsRecognizer.main(AutomaticTermsRecognizer.scala)
:recognize FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recognize'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

The WORKING_DIRECTORY of my project is as below:
![image](https://user-images.githubusercontent.com/4690174/35263832-53c39550-0055-11e8-8010-3ba87423f57b.png)

please provide a complete tutorial for this tool?

**Comment by astrakhantsev** [comment]
> Exception in thread "main" java.io.FileNotFoundException: CValue.conf (No such file or directory)

Move CValue.conf file to the working directory.

**Comment by xiaoxielnino** [comment]
![image](https://user-images.githubusercontent.com/4690174/35333066-4a6fc4e4-0148-11e8-9f88-224b12d8ecac.png)
after moved the CValue.conf to the working directory, the above error occurred. How to specify the exact parameter in the command line? I afraid another error will occur if this parameter solved.
Could you provide a complete example please?

**Comment by astrakhantsev** [comment]
Now it can't find `acl2` directory or considers this to be not a directory. 
Is your working directory `experiments` or is it some folder, which contains `experiments`? If it is the former, i.e. if `acl2` is a subfolder of the working directory, the error is not reproduced.

> How to specify the exact parameter in the command line?

What do you mean by that?

**Comment by xiaoxielnino** [comment]
![image](https://user-images.githubusercontent.com/4690174/35373381-15327b14-01d9-11e8-829c-46dc8b6a1a2e.png)
Here is the usage of the tool.
The below picture is my project structure.
![image](https://user-images.githubusercontent.com/4690174/35373450-66788d74-01d9-11e8-9286-486bb0a11c4d.png)
the ac12 is subdirectory of experiments, and the ac12 directiory contains the  CValue.conf file. 
And I ran this command-- "./gradlew recognize -Pdataset=acl2 -PtopCount=10 -Pconfig=CValue.conf -Poutput=cvalueterms.txt" -- on the atr4s root directory.
 I assumed that the atr4s is the working_directory, and the ./gradlew command only works on the root directory.
So, here is my problem: If i ran the command on the atr4s root directory, which one is my WORKING_DIRECTORY?  The experiments one(subdirectory of atr4s) or the art4s? And then which directory should be the ac12 directory and the CValue.conf on?
So much thanks for your time.

**Comment by xiaoxielnino** [comment]
![image](https://user-images.githubusercontent.com/4690174/35373857-6b0a870a-01db-11e8-8ab8-1acac4ec074c.png)

Here is the usage of the tool.
The below picture is my project structure.
![image](https://user-images.githubusercontent.com/4690174/35373795-1c27d91c-01db-11e8-99ae-bfb0c5c3c337.png)
the ac12 is subdirectory of experiments, and the ac12 directiory contains the CValue.conf file.
And I ran this command-- "./gradlew recognize -Pdataset=acl2 -PtopCount=10 -Pconfig=CValue.conf -Poutput=cvalueterms.txt" -- on the atr4s root directory.
I assumed that the atr4s is the working_directory, and the ./gradlew command only works on the root directory.
So, here is my problem: 

- If i ran the command on the atr4s root directory, which one is my WORKING_DIRECTORY? The experiments one(subdirectory of atr4s) or the art4s? 

- And then which directory should be the ac12 directory and the CValue.conf on?

So much thanks for your time.

**Comment by astrakhantsev** [comment]
> note that working directory can be specified in gradle.properties - by default, this is experiments

To be more precise, if you don't change `gradle.properties` (which you seemed to do, given the blue color - note that `atr_recognize_wd` property indicates the working directory) and run the command on `atr4s` directory, then WORKING_DIRECTORY would be `atr4s/experiments`. Both `acl2` and `CValue.conf` should be placed to WORKING_DIRECTORY, i.e. into atr4s/experiments. `acl2` should contain only text documents.

Please, try to run with these settings and let me know what will happen.

**Comment by xiaoxielnino** [comment]
It seems work now. But there is still the encoding problem. I've tried the [tool](http://stackoverflow.com/questions/64860/best-way-to-convert-text-files-between-character-sets) of the github page, But it seems not work. I now try the other methods. If there is any recommended method, it will be a great of help.
![image](https://user-images.githubusercontent.com/4690174/35553195-ccf16250-05d1-11e8-8781-cd992c6792e6.png)

**Comment by astrakhantsev** [comment]
Looks like `.DS_Store` isn't a text file, but some service file (see [wiki](https://en.wikipedia.org/wiki/.DS_Store)), so it is not an encoding problem. Most probably, you should just (re)move this file.
