### ISSUE TITLE
how to generate term candidates from the dataset

### ISSUE THREAD

**Issue by xiaoxielnino** [ispras/atr4s#7]
the example useage of the project is **./gradlew recognize -Pdataset=acl2 -PtopCount=10 -Pconfig=CValue.conf -Poutput=cvalueterms.txt**
And I noticed that the recognize task must use the topCount parameter. But If I just want to use the specific conf(e.g.  LinkProbability.conf) to generate all the term candidates and compared to the hand  labeld candidates, **which steps or task should I do in this project?**

Is it the only task recognize to generate top count terms?

**Comment by astrakhantsev** [comment]
If you want to extract all term candidates, just specify notoriously large number, e.g. 2,000,000,000 (or even max int): 
`./gradlew recognize -Pdataset=acl2 -PtopCount=2000000000 -Pconfig=LinkProbability.conf -Poutput=all_term_candidate_with_linkprob_weight.txt`
In this case, all term candidates sorted by LinkProbability weight will be returned.

**Comment by xiaoxielnino** [comment]
After extract all the term candidates, I found that there are a lot of weightTerms ended with 0.0(LinkProbability.conf), which are less than 1 or equal to 1. While using the Cvalue.conf, the top ranked candidates are larger than 1. so,

- What does the number ended with the weightTerm mean?

- What does the number ended with the weightTerm mean when it equals to 0.0?

**Comment by astrakhantsev** [comment]
Number means weight of the corresponding term candidate. This weights are not normalized. Usually, 0.0 means that this particular term weighter (i.e. feature, e.g. CValue or LinkProbability) considers this candidate to be not a term.
