### ISSUE TITLE
info-measure issue

### ISSUE THREAD

**Issue by xiaoxielnino** [ispras/atr4s#8]
Recently, I read the source code of LinkProbability method for term scoring. And I got confuse about the meaning of the info-measure file. 
In every line of the file, the first part represents the number of hyperlink caption, and the second represent the number of  occurrences in wikipedia pages.

- What  is the meaning of the third part in every line of info-measure?

- Is it represent the title of wikipedia articles?

- Could you explain the source of the info-measure.txt file or provide the source of how to generate the info-measure.txt file?

**Comment by astrakhantsev** [comment]
Sorry for the delay; yes, the third column is a normalized title of wikipedia article. This file was created from [wikipedia dump](https://en.wikipedia.org/wiki/Wikipedia:Database_download) several years ago by using 3rd party tool, which wasn't open sourced, unfortunately.
